// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace WellDone
{
    internal sealed partial class Vsix
    {
        public const string Id = "WellDone.ec3f963d-1054-4e12-92da-2efccb30228d";
        public const string Name = "Well Done!";
        public const string Description = @"The best way to support during difficult work";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Aleksandr Dashkevich";
        public const string Tags = "";
    }
}
